### PR TITLE
Updated some dependencies added fivem.js

### PR DESCRIPTION
**Pull request by Dreaming-Codes**

### CODE REVIEW

**Review by lucasmathioni — APPROVED** [review]

**Review by xFutte — APPROVED** [review]
Looks good to me.

**Comment by IzioDev** [comment]
Need to change `--watch true` to `--watch` in watch script defined in package.json, else watcher isn't working for me.

Probably a change due to Webpack 4 -> 5

**Comment by S33G** [comment]
As this has not been merged, I assume mine will not also. 
Although, here's an even more recent one :)

https://github.com/d0p3t/fivem-ts-boilerplate/pull/9

**Comment by Dreaming-Codes** [comment]
> As this has not been merged, I assume mine will not also. 
> Although, here's an even more recent one :)
> 
> https://github.com/d0p3t/fivem-ts-boilerplate/pull/9

Unfortunately, the owner of this repo is no longer with us....

**Comment by S33G** [comment]
Thanks for letting me know @Dreaming-Codes 
I've spun up a new repo based on this, I'll happily keep this up to date.
Feel free to get involved :)

https://github.com/True-Core/fivem-typescript-starter

**Pull request closed without merging**
