### PR TITLE
package.json library updates

### PR DESCRIPTION
**Pull request by Lxk3y**
Updated all libraries to the latest version (to prevent people cloning ancient versions of libraries and the citizenfx types) as well as removed a deprecated library 'eslint-loader', replacing it with its new version, 'eslint-webpack-plugin'. Tested building a resource on my end with all these updates in place and built successfully.

### CODE REVIEW

**Comment by Lxk3y** [comment]
Aha it appears i forgot to push the package-lock.json file hence the build failure

**Comment by d0p3t** [comment]
Have you checked if building with webpack 5.0 works fine and runs on FiveM? I have had many issues with upgrading to 5.0 as well as other people.

**Comment by Lxk3y** [comment]
> Have you checked if building with webpack 5.0 works fine and runs on FiveM? I have had many issues with upgrading to 5.0 as well as other people.

I will double check these things with you this afternoon and get back to you

**Comment by Lxk3y** [comment]
> > Have you checked if building with webpack 5.0 works fine and runs on FiveM? I have had many issues with upgrading to 5.0 as well as other people.
> 
> I will double check these things with you this afternoon and get back to you

Ok so after further testing, Webpack 5 seems to work for me at least if i build my resources locally (Tested on 2 resources coded myself) and then just chuck the fxmanifest and the dist folder into a resource folder and run it. However having FXServer build it automatically does seem to cause errors triggering a build failure. Perhaps you could try building a resource locally with Webpack 5 and seeing if it works for you?

**Pull request closed without merging**
